
import SymbolicDynamics.ShiftSpace
import SymbolicDynamics.Blocks

-- Subshifts of finite types

def appears_anywhere [Mul X] (u: X → Y) (b: Block X Y): Prop :=
  ∃ x: X, appears (shift x u) b

def shift_from_forbidden_block [Mul X] (b: Block X Y): Set (X → Y) :=
  {u | ¬ appears_anywhere u b}

def shift_from_forbidden_blocks [Mul X] (F: Set (Block X Y)): Set (X → Y) :=
  {u | ∀ b ∈ F, ¬ appears_anywhere u b}

example [Mul X] (F: Set (Block X Y)):
  shift_from_forbidden_blocks F = Set.sInter (Set.image (fun b => shift_from_forbidden_block b) F) := by
  simp [shift_from_forbidden_block, shift_from_forbidden_blocks]
  ext
  simp_all

-- use some facts about open sets
/-
{u: T → A | appears u ⟨Ω, f⟩}
 = take the union over all configs containing Ω
 = union over v containing ⟨Ω, f⟩ { u: T → A | u|Ω = v|Ω }



-/


def containing (b: Block X Y): Set (X → Y) :=
  {u: X → Y | appears u b}

theorem eqOn_lemma {u v: X → Y} {Ω: Set X}:
  Set.EqOn u v Ω ↔ Ω.restrict u = Ω.restrict v := by
  simp_all only [Set.restrict_eq_restrict_iff]

theorem IsOpen_appears [TopologicalSpace A] [DiscreteTopology A]
  {Ω: Set T} (f: Ω → A) (h: Finite Ω):
  IsOpen {u: T → A | appears u ⟨Ω, f⟩} := by
  have: {u: T → A | appears u ⟨Ω, f⟩} = Set.sUnion (Set.image (fun v => eqOn_nhd v Ω) (containing ⟨Ω, f⟩)) := by
    ext x
    constructor
    . intro hx
      simp
      exists x
      constructor
      . simp_all
        exact hx
      . exact eqOn_nhd_self x Ω
    . simp
      intro x' hx' h1
      simp_all [appears, eqOn_nhd, containing]
      rw [← Set.restrict_eq_restrict_iff] at h1
      rw [← h1]
      exact hx'
  rw [this]
  apply isOpen_sUnion
  intro U hU
  obtain ⟨x, hx⟩ := hU
  rw [←hx.right]
  exact eqOn_nhd_open x h

def shift_set [Mul X] (t: X) (S: Set X): Set X := Set.image (fun x => t * x) S

noncomputable def shift_block [Mul X] (t: X) (b: Block X Y): Block X Y := ⟨shift_set t b.fst , fun ⟨_, hx⟩ => b.snd ⟨Classical.choose hx, (Classical.choose_spec hx).left⟩⟩

theorem appears_shift_iff [Mul X] (t: X) (b: Block X Y):
  appears (shift t u) b ↔ appears u (shift_block t b) := by
  constructor
  intro h
  simp_all [shift_block, shift_set, appears]
  rw [← h]
  ext x
  simp [shift, leftMul]
  sorry
  sorry

theorem IsOpen_appears_shift [Mul T] [TopologicalSpace A] [DiscreteTopology A]
  {Ω: Set T} (f: Ω → A) (h: Finite Ω) (t: T):
  IsOpen {u: T → A | appears (shift t u) ⟨Ω, f⟩} := by
  sorry


-- 1.47.a
theorem shift_from_forbidden_blocks_is_shift [Monoid X] [TopologicalSpace Y] (F: Set (Block X Y))
  (h: ∀ b ∈ F, Finite b.fst):
  ShiftSpace (shift_from_forbidden_blocks F) := {
  closed := by
    rw [shift_from_forbidden_blocks]
    apply IsClosed.mk
    have: {u | ∀ b ∈ F, ¬appears_anywhere u b}ᶜ = {u | ∃ b ∈ F, appears_anywhere u b} := by
      ext
      simp
    rw [this]
    have: {u | ∃ b ∈ F, appears_anywhere u b} = Set.sUnion (Set.image (fun b => {u | appears_anywhere u b}) F) := by
      ext
      simp
    rw [this]
    apply isOpen_sUnion
    intro _ hU
    obtain ⟨b, hb⟩ := hU
    simp [←hb.right, appears_anywhere]
    have: {u | ∃ x, appears (shift x u) b} = Set.sUnion (Set.image (fun x => {u | appears (shift x u) b}) Set.univ) := by
      ext
      simp
    simp [this]
    apply isOpen_sUnion
    intro _ hV
    obtain ⟨t, ht⟩ := hV
    simp [←ht]
    sorry
  shift_invariant := by
    intro u hu x b hb
    specialize hu b hb
    simp_all [appears_anywhere]
    intro x'
    simp_all [appears, shift, leftMul, Function.comp]
    specialize hu (x * x')
    intro h
    apply hu
    rw [←h]
    simp [Set.EqOn]
    intro _ _
    rw [mul_assoc]
  }

-- definition of F(X)
def patterns_not_found_in
  (U: Set (X → Y)): Set (Block X Y) :=
  Set.compl (blocks_in_configs U)

-- 1.47.b
theorem defining_set_eq [Mul X] [TopologicalSpace Y] (U: Set (X → Y)) (h: Subshift U):
  U = shift_from_forbidden_blocks (patterns_not_found_in U) := by
  sorry

theorem defining_set_contained [Mul X] [TopologicalSpace Y]
  (U: Set (X → Y)) (h: Subshift U) (F: Set (Block X Y)) (hF: U = shift_from_forbidden_blocks F):
  F ⊆ patterns_not_found_in U := by
  sorry


-- TODO: 1.47.c

-- Let U ⊆ (X → Y)
-- Then U is said to have "finite type" if it is generated by a finite set of forbidden blocks
def Subshift_of_finite_type [Mul X] [TopologicalSpace Y] (U: Set (X → Y)): Prop :=
  ∃ F: Set (Block X Y), Finite F ∧ U = shift_from_forbidden_blocks F

-- TODO: 1.48.a

-- 1.48.b
-- Let 𝔸 ⊆ (Ω → A) be a set of "admissible patterns"
-- This is the set X(𝔸) = {x | ∀ t, (shift t x)|Ω ∈ 𝔸}
def subshift_from_admissible_patterns {T A: Type*} [Mul T] {Ω: Set T} (𝔸: Set (Ω → A)): Set (T → A) :=
  {x | ∀ t, Ω.restrict (shift t x) ∈ 𝔸}

-- Suppose A and Ω are finite. Then X(𝔸) is a subshift of finite type.
theorem subshift_from_admissible_patterns_finite_type {T A: Type*} [TopologicalSpace A] [Finite A] [Mul T] {Ω: Set T} [Finite Ω] (𝔸: Set (Ω → A)):
  Subshift_of_finite_type (subshift_from_admissible_patterns 𝔸) := by
  exists {⟨Ω, f⟩ | f ∈ Set.compl 𝔸}
  constructor
  . let φ: {b: Block T A | ∃ f ∈ 𝔸.compl, ⟨Ω, f⟩ = b} → (Ω → A) := fun ⟨⟨_, f⟩, hb⟩ x => by
      rw [←(Sigma.mk.inj_iff.mp (Classical.choose_spec hb).right).left] at f
      exact f x
    apply Finite.of_injective φ
    intro x1 x2 hx
    simp [φ] at hx
    obtain ⟨_, hx1⟩ := x1
    obtain ⟨_, hx2⟩ := x2
    obtain ⟨_, hf1⟩ := hx1
    obtain ⟨_, hf2⟩ := hx2
    obtain ⟨_, hf1b⟩ := hf1
    obtain ⟨_, hf2b⟩ := hf2
    subst hf2b hf1b
    simp_all [cast_eq]
  . simp [subshift_from_admissible_patterns, shift_from_forbidden_blocks, appears_anywhere, appears]
    ext x
    constructor
    . intro h p hp t
      apply Not.intro
      intro h1
      rw [←h1] at hp
      specialize h t
      contradiction
    . intro h t
      by_contra h'
      specialize h (Ω.restrict (shift t x)) h' t
      exact h rfl

-- 1.48.e
theorem subshift_of_finite_type_univ [Mul X] [TopologicalSpace Y]:
  Subshift_of_finite_type (@Set.univ (X → Y)) := by
  exists ∅
  constructor
  exact Set.finite_empty
  simp [shift_from_forbidden_blocks]

-- 1.48.f
-- intersection of subshfits of finite type is a subshift with finite type
theorem subshift_of_finite_type_inter [Mul X] [TopologicalSpace Y]
  {Λ1 Λ2: Set (X → Y)} (h1: Subshift_of_finite_type Λ1) (h2: Subshift_of_finite_type Λ2):
  Subshift_of_finite_type (Λ1 ∩ Λ2) := by
  obtain ⟨F1, hF1⟩ := h1
  obtain ⟨F2, hF2⟩ := h2
  exists F1 ∪ F2
  constructor
  exact @Finite.Set.finite_union _ F1 F2 hF1.left hF2.left
  rw [hF1.right, hF2.right]
  ext
  constructor
  intro ⟨hu1, hu2⟩ b h
  cases h
  case inl h' => exact hu1 b h'
  case inr h' => exact hu2 b h'
  intro h
  constructor
  · exact fun b hb => h b (Or.inl hb)
  · exact fun b hb => h b (Or.inr hb)

-- Given y: Y, consider the constant map u: _ => y.
-- Show the subshift X = {u} is a subshift of finite type.
theorem subshift_of_finite_type_singleton [Mul X] [TopologicalSpace Y]
  {y: Y}: Subshift_of_finite_type {fun _: X=> y} := by
  -- We'll use a block that covers all of X and maps to y
  sorry
